package telegram

import (
	"slices"
)

// CheckActions проверка действия
func CheckActions(action string) bool {
	actions := []string{
		"getUpdates",
		"setWebhook",
		"deleteWebhook",
		"getWebhookInfo",
		"getMe",
		"sendMessage",
		"forwardMessage",
		"sendPhoto",
		"sendAudio",
		"sendDocument",
		"sendSticker",
		"sendVideo",
		"sendAnimation",
		"sendVoice",
		"sendVideoNote",
		"sendMediaGroup",
		"sendLocation",
		"editMessageLiveLocation",
		"stopMessageLiveLocation",
		"sendVenue",
		"sendContact",
		"sendPoll",
		"sendDice",
		"sendChatAction",
		"getUserProfilePhotos",
		"getFile",
		"kickChatMember",
		"unbanChatMember",
		"restrictChatMember",
		"promoteChatMember",
		"setChatAdministratorCustomTitle",
		"setChatPermissions",
		"exportChatInviteLink",
		"setChatPhoto",
		"deleteChatPhoto",
		"setChatTitle",
		"setChatDescription",
		"pinChatMessage",
		"unpinChatMessage",
		"leaveChat",
		"getChat",
		"getChatAdministrators",
		"getChatMembersCount",
		"getChatMember",
		"setChatStickerSet",
		"deleteChatStickerSet",
		"answerCallbackQuery",
		"answerInlineQuery",
		"setMyCommands",
		"getMyCommands",
		"editMessageText",
		"editMessageCaption",
		"editMessageMedia",
		"editMessageReplyMarkup",
		"stopPoll",
		"deleteMessage",
		"getStickerSet",
		"uploadStickerFile",
		"createNewStickerSet",
		"addStickerToSet",
		"setStickerPositionInSet",
		"deleteStickerFromSet",
		"setStickerSetThumb",
		"sendInvoice",
		"answerShippingQuery",
		"answerPreCheckoutQuery",
		"setPassportDataErrors",
		"sendGame",
		"setGameScore",
		"getGameHighScores",
	}

	return slices.Contains(actions, action)
}
